### ISSUE TITLE
Crash when loading with Framed Blocks

### ISSUE THREAD

**Issue by Paulie820** [teaconmc/XKDeco#31] opened 2024-05-07 08:00 UTC
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

0.5.4

### Modloader version

Forge 47.2.29

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/MyBhxvCL

### Issue description

When loading XK Decor with FramedBlocks, a loading error occurs at the sided_setup phase, causing a failure to load into the game. Reading from the crash some blocks are lacking blockitems which I assume are trying to be called on by FB. I know this mod was just recently ported, if this is something that will be added in an upcoming version I can close this issue.

**Comment by Snownee** [comment] 2024-05-07 08:45
![image](https://github.com/teaconmc/XKDeco/assets/16059084/a8433ebd-ce6c-4135-81fd-65bca9fcb0c5)

**Comment by Paulie820** [comment] 2024-05-07 19:20
> ![image](https://private-user-images.githubusercontent.com/16059084/328453449-a8433ebd-ce6c-4135-81fd-65bca9fcb0c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDM0MzcsIm5iZiI6MTcxNTEwMzEzNywicGF0aCI6Ii8xNjA1OTA4NC8zMjg0NTM0NDktYTg0MzNlYmQtY2U2Yy00MTM1LTgxZmQtNjViY2E5ZmNiMGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE3MzIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZmExYzRjNjgxY2RmN2FjNDkxYTg0ZWIxZTU1MzhiNGU1YjEzNzZiNGViNTQ4YTBkZjQ4NDY5NTNmNDU0MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.efrc9o2wSwauZv6Jb4btv13pO5ZUUzYapK00Y4xGHYQ)

Alright so looking further into it, when I have FramedBlocks, XK, **and** Amendments installed it throws up the BlockItem issue. I take out XK and there is no issue, I take out Amendments no issue, I take out FramedBlocks no issue. 

Should I close this and raise the issue with one of the other two?

Latest log: https://justpaste.it/eqwd5

**Comment by Snownee** [comment] 2024-05-07 21:27
thank you for finding it out, now I can reproduce it. I've wasted an hour on it and still don't know what is the cause. maybe you should report it to the author of FramedBlocks

**Comment by XFactHD** [comment] 2024-05-17 01:09
This is an interaction between Kiwi and Moonlight (which Amendments depends on) and a check in FramedBlocks just makes the issue visible: Kiwi creates a `MultiPackResourceManager` during the `RegisterEvent` for blocks. This resource manager is marked as "client resources" and contains all client resources bundled in mods due to the call to Forge's `ResourcePackLoader.loadResourcePacks()` (https://github.com/Snownee/Kiwi/blob/8d4629786f9831eabd6d056603517f095757812b/src/main/java/snownee/kiwi/customization/CustomizationHooks.java#L361-L376). Moonlight has a mixin at the tail of the `MultiPackResourceManager` constructor which checks for the presence of a marker file and then executes an "early load" callback (https://github.com/MehVahdJukaar/Moonlight/blob/4f4390219b95d5ae257192a884bbeacd3d021014/common/src/main/java/net/mehvahdjukaar/moonlight/core/mixins/MultiPackResourceManagerMixin.java). Due to all mod assets being included in this "custom" resource manager, Moonlight finds that marker file and runs the callback (which it expects to happen far later than the block registry event). This fires an event and ultimately ends up in Amendments' `WallLanternResourceManager` which iterates the block registry, calls `Block#asItem()` on all blocks and poisons the partially cached block-to-item conversion by doing so that early (https://github.com/MehVahdJukaar/amendments/blob/847fd7ff34fb0f6082a3dd67cd4053cec948a25d/common/src/main/java/net/mehvahdjukaar/amendments/client/WallLanternModelsManager.java#L93-L100). Later on when I register my "ghost render behaviors" in the client setup event in FramedBlocks, the result of `Block#asItem()` (which incorrectly returns air now) is caught by a precondition that makes sure only valid blocks are registered (https://github.com/XFactHD/FramedBlocks/blob/220e2e70536c0bd0cee4130732d2e00efd10e8cb/src/main/java/xfacthd/framedblocks/client/render/special/GhostBlockRenderer.java#L261).
The problematic call stack in the debugger:
![grafik](https://github.com/teaconmc/XKDeco/assets/11262040/3de379e3-9d77-4ad4-a657-3de7c22ae914)

**Comment by Snownee** [comment] 2024-05-17 09:17
@XFactHD Thank you so much for pointing it out. I think I have fixed it now by making a copy of the `MultiPackResourceManager` so that the mixins will not take effect.

**Closed as completed** 2024-05-17 09:16 UTC
